version: "3"
services:
  mongodb:
    image: mongo
    networks:
      - app-network
    logging:
      driver: none
  node:
    build:
      dockerfile: ./dockerfile
      context: .
    image: alexandre/node-clients
    container_name: node-clients
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - "mongodb"
    command: >
      sh -c "yarn seed && yarn test && yarn start"
networks:
  app-network:
    driver: bridge
